export default [
	{
		id: 12,
		buildingId: 1,
		buildingName: 'APEX Systems México',
		floorId: 1,
		floorName: 'Piso 18',
		zoneId: 1,
		zoneName: 'Dinning Room, Kitchen and Reception',
		workStationId: 1,
		workStationName: 'WorkStation A',
		areaByFigure: {
			id: 13,
			figureId: 1,
			figureName: 'Rectangle',
			description: 'desktop',
			height: 1,
			width: 1,
			radius: null,
			points: null,
		},
		employeeId: 192,
		firstName: 'Marco ',
		lastName: 'Mendieta',
		x: 0,
		y: 9,
		seatState: {
			id: 2,
			name: 'In Use',
			description: 'A local employee is using this seat currently',
		},
		description: null,
		links: null,
	},
	{
		id: 4,
		buildingId: 1,
		buildingName: 'APEX Systems México',
		floorId: 1,
		floorName: 'Piso 18',
		zoneId: 1,
		zoneName: 'Dinning Room, Kitchen and Reception',
		workStationId: 1,
		workStationName: 'WorkStation A',
		areaByFigure: {
			id: 13,
			figureId: 1,
			figureName: 'Rectangle',
			description: 'desktop',
			height: 1,
			width: 1,
			radius: null,
			points: null,
		},
		employeeId: 191,
		firstName: 'Julio ',
		lastName: 'Abarca',
		x: 0,
		y: 20,
		seatState: {
			id: 2,
			name: 'In Use',
			description: 'A local employee is using this seat currently',
		},
		description: null,
		links: null,
	},
	{
		id: 6,
		buildingId: 1,
		buildingName: 'APEX Systems México',
		floorId: 1,
		floorName: 'Piso 18',
		zoneId: 1,
		zoneName: 'Dinning Room, Kitchen and Reception',
		workStationId: 1,
		workStationName: 'WorkStation A',
		areaByFigure: {
			id: 13,
			figureId: 1,
			figureName: 'Rectangle',
			description: 'desktop',
			height: 1,
			width: 1,
			radius: null,
			points: null,
		},
		employeeId: 208,
		firstName: 'Ruben ',
		lastName: 'Rodriguez',
		x: 1,
		y: 20,
		seatState: {
			id: 2,
			name: 'In Use',
			description: 'A local employee is using this seat currently',
		},
		description: null,
		links: null,
	},
	{
		id: 7,
		buildingId: 1,
		buildingName: 'APEX Systems México',
		floorId: 1,
		floorName: 'Piso 18',
		zoneId: 1,
		zoneName: 'Dinning Room, Kitchen and Reception',
		workStationId: 1,
		workStationName: 'WorkStation A',
		areaByFigure: {
			id: 13,
			figureId: 1,
			figureName: 'Rectangle',
			description: 'desktop',
			height: 1,
			width: 1,
			radius: null,
			points: null,
		},
		employeeId: 222,
		firstName: 'Crystian ',
		lastName: 'Carranco',
		x: 2,
		y: 20,
		seatState: {
			id: 2,
			name: 'In Use',
			description: 'A local employee is using this seat currently',
		},
		description: null,
		links: null,
	},
	{
		id: 10,
		buildingId: 1,
		buildingName: 'APEX Systems México',
		floorId: 1,
		floorName: 'Piso 18',
		zoneId: 1,
		zoneName: 'Dinning Room, Kitchen and Reception',
		workStationId: 1,
		workStationName: 'WorkStation A',
		areaByFigure: {
			id: 13,
			figureId: 1,
			figureName: 'Rectangle',
			description: 'desktop',
			height: 1,
			width: 1,
			radius: null,
			points: null,
		},
		employeeId: 167,
		firstName: 'Miguel ',
		lastName: 'Martinez',
		x: 3,
		y: 9,
		seatState: {
			id: 2,
			name: 'In Use',
			description: 'A local employee is using this seat currently',
		},
		description: null,
		links: null,
	},
	{
		id: 8,
		buildingId: 1,
		buildingName: 'APEX Systems México',
		floorId: 1,
		floorName: 'Piso 18',
		zoneId: 1,
		zoneName: 'Dinning Room, Kitchen and Reception',
		workStationId: 1,
		workStationName: 'WorkStation A',
		areaByFigure: {
			id: 13,
			figureId: 1,
			figureName: 'Rectangle',
			description: 'desktop',
			height: 1,
			width: 1,
			radius: null,
			points: null,
		},
		employeeId: 231,
		firstName: 'Alex ',
		lastName: 'Gutierrez',
		x: 3,
		y: 20,
		seatState: {
			id: 2,
			name: 'In Use',
			description: 'A local employee is using this seat currently',
		},
		description: null,
		links: null,
	},
	{
		id: 15,
		buildingId: 1,
		buildingName: 'APEX Systems México',
		floorId: 1,
		floorName: 'Piso 18',
		zoneId: 1,
		zoneName: 'Dinning Room, Kitchen and Reception',
		workStationId: 2,
		workStationName: 'Workstation B',
		areaByFigure: {
			id: 13,
			figureId: 1,
			figureName: 'Rectangle',
			description: 'desktop',
			height: 1,
			width: 1,
			radius: null,
			points: null,
		},
		employeeId: 192,
		firstName: 'Marco ',
		lastName: 'Mendieta',
		x: 0,
		y: 9,
		seatState: {
			id: 2,
			name: 'In Use',
			description: 'A local employee is using this seat currently',
		},
		description: null,
		links: null,
	},
	{
		id: 14,
		buildingId: 1,
		buildingName: 'APEX Systems México',
		floorId: 1,
		floorName: 'Piso 18',
		zoneId: 1,
		zoneName: 'Dinning Room, Kitchen and Reception',
		workStationId: 2,
		workStationName: 'Workstation B',
		areaByFigure: {
			id: 13,
			figureId: 1,
			figureName: 'Rectangle',
			description: 'desktop',
			height: 1,
			width: 1,
			radius: null,
			points: null,
		},
		employeeId: 209,
		firstName: 'Carlos ',
		lastName: 'Padilla',
		x: 1,
		y: 9,
		seatState: {
			id: 4,
			name: 'Pool seat',
			description: 'A local employee is using this seat currently',
		},
		description: null,
		links: null,
	},
	{
		id: 16,
		buildingId: 1,
		buildingName: 'APEX Systems México',
		floorId: 1,
		floorName: 'Piso 18',
		zoneId: 1,
		zoneName: 'Dinning Room, Kitchen and Reception',
		workStationId: 2,
		workStationName: 'Workstation B',
		areaByFigure: {
			id: 13,
			figureId: 1,
			figureName: 'Rectangle',
			description: 'desktop',
			height: 1,
			width: 1,
			radius: null,
			points: null,
		},
		employeeId: null,
		firstName: null,
		lastName: null,
		x: 2,
		y: 10,
		seatState: {
			id: 1,
			name: 'Available',
			description: 'Empty seat wating to be used',
		},
		description: null,
		links: null,
	},
	{
		id: 9,
		buildingId: 1,
		buildingName: 'APEX Systems México',
		floorId: 1,
		floorName: 'Piso 18',
		zoneId: 1,
		zoneName: 'Dinning Room, Kitchen and Reception',
		workStationId: 2,
		workStationName: 'Workstation B',
		areaByFigure: {
			id: 13,
			figureId: 1,
			figureName: 'Rectangle',
			description: 'desktop',
			height: 1,
			width: 1,
			radius: null,
			points: null,
		},
		employeeId: 232,
		firstName: 'Karen ',
		lastName: 'Valdivia',
		x: 3,
		y: 10,
		seatState: {
			id: 2,
			name: 'In Use',
			description: 'A local employee is using this seat currently',
		},
		description: null,
		links: null,
	},
];
